//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1091415_project1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarTable
    {
        public System.Guid ID { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public Nullable<int> Year { get; set; }
        public string Uso { get; set; }
    }
}
