//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Multa
    {
        public string Acta { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Cedula { get; set; }
        public string Infraccion { get; set; }
        public string Estado { get; set; }
        public string Precio { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public System.Guid Id { get; set; }
    }
}
